# 使用GitHub Actions在Windows上自动打包

name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        pip install pyarmor==9.1.9
    
    - name: Obfuscate code with PyArmor
      run: |
        python -m pyarmor gen --output dist_protected document_processor.py license_manager.py
        copy dist_protected\document_processor.py document_processor.py
        copy dist_protected\license_manager.py license_manager.py
        xcopy /E /I dist_protected\pyarmor_runtime_000000 pyarmor_runtime_000000
        
    - name: Build executable
      run: pyinstaller document_processor.spec
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DocumentProcessor-Windows
        path: dist/DocumentProcessor.exe
        retention-days: 30

# 使用方法：
# 1. 在GitHub上创建仓库
# 2. 将代码推送到仓库
# 3. 在Actions标签页下载打包好的exe文件
